#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pytest_localserver
Version  : 0.6.0
Release  : 32
URL      : https://files.pythonhosted.org/packages/fe/51/e13cfcf43b512eddbd96658ef6bff6f1a5911c2f3882aaf64998a8e10ac8/pytest-localserver-0.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fe/51/e13cfcf43b512eddbd96658ef6bff6f1a5911c2f3882aaf64998a8e10ac8/pytest-localserver-0.6.0.tar.gz
Summary  : py.test plugin to test server connections locally.
Group    : Development/Tools
License  : MIT
Requires: pypi-pytest_localserver-license = %{version}-%{release}
Requires: pypi-pytest_localserver-python = %{version}-%{release}
Requires: pypi-pytest_localserver-python3 = %{version}-%{release}
Requires: pypi(werkzeug)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(aiosmtpd)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(werkzeug)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
==================
pytest-localserver
==================
pytest-localserver is a plugin for the `pytest`_ testing framework which enables
you to test server connections locally.

%package license
Summary: license components for the pypi-pytest_localserver package.
Group: Default

%description license
license components for the pypi-pytest_localserver package.


%package python
Summary: python components for the pypi-pytest_localserver package.
Group: Default
Requires: pypi-pytest_localserver-python3 = %{version}-%{release}

%description python
python components for the pypi-pytest_localserver package.


%package python3
Summary: python3 components for the pypi-pytest_localserver package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_localserver)
Requires: pypi(aiosmtpd)
Requires: pypi(werkzeug)

%description python3
python3 components for the pypi-pytest_localserver package.


%prep
%setup -q -n pytest-localserver-0.6.0
cd %{_builddir}/pytest-localserver-0.6.0
pushd ..
cp -a pytest-localserver-0.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656400976
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pytest_localserver
cp %{_builddir}/pytest-localserver-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pytest_localserver/51ba379b1f8a00dcce471b472d18bf55e1c9b734
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pytest_localserver/51ba379b1f8a00dcce471b472d18bf55e1c9b734

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
